spring.application.name=Mary-s
# ==========================================
# CONEXIÓN A LA BASE DE DATOS (MySQL)
# ==========================================

# 1. Ubicación de la base de datos
# Agregamos 'createDatabaseIfNotExist=true' para que Spring cree la base si no existe.
# 'produbanco_next' es el nombre de tu base de datos.
spring.datasource.url=jdbc:mysql://localhost:3306/mary_barbershop?createDatabaseIfNotExist=true&serverTimezone=UTC

# 2. Usuario de la base de datos
spring.datasource.username=root

# 3. Contraseña de la base de datos
# Nota: Asegúrate de que no haya espacios al final de esta línea.
spring.datasource.password=

# 4. Driver (El traductor para que Java hable con MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================

# 5. Estrategia de creación de tablas
# 'update' sincroniza tus clases de Java con las tablas de SQL automáticamente.
spring.jpa.hibernate.ddl-auto=update

# 6. Mostrar consultas SQL en consola
# Útil para ver qué está haciendo Java "detrás de cámaras".
spring.jpa.show-sql=true

# 7. Dialecto (ESTA LÍNEA ES CLAVE)
# Le dice a Hibernate exactamente qué "versión" de SQL hablar. 
# Esto resuelve el error "Unable to determine Dialect" que tenías en el log.
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================================
# manera de auterisar contrasenal al administrador...
#==================================
spring.security.user.name=admin
spring.security.user.password=12345



